FROM node:20-slim

WORKDIR /app

ENV NODE_ENV=development

COPY franes/package*.json ./

RUN npm install --legacy-peer-deps

COPY franes/ .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
