"""add admin users table

Revision ID: 134a2d71f887
Revises: 747776439275
Create Date: 2025-10-16 09:52:36.133089

"""



# revision identifiers, used by Alembic.
revision = "134a2d71f887"
down_revision = "747776439275"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
