"""add curriculum files

Revision ID: 6db68d6321aa
Revises: da18f0b44246
Create Date: 2025-10-16 07:22:48.862501

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6db68d6321aa"
down_revision = "da18f0b44246"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("art", sa.Column("image", sa.JSON(), nullable=True))
    op.add_column("story_script", sa.Column("cover_image", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_script", "cover_image")
    op.drop_column("art", "image")
    # ### end Alembic commands ###
