"""create migration new art 2

Revision ID: 6f419c4d57d8
Revises: 8dd51b079752
Create Date: 2025-10-07 07:43:57.883583

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f419c4d57d8"
down_revision = "8dd51b079752"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "art", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "art", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    # ### end Alembic commands ###
