"""create initial tables

Revision ID: d4745a74668c
Revises: 134a2d71f887
Create Date: 2025-10-16 11:01:22.950100

"""



# revision identifiers, used by Alembic.
revision = "d4745a74668c"
down_revision = "134a2d71f887"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
