"""add admin users

Revision ID: 747776439275
Revises: 6db68d6321aa
Create Date: 2025-10-16 07:47:28.903593

"""



# revision identifiers, used by Alembic.
revision = "747776439275"
down_revision = "6db68d6321aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
