"""story script model

Revision ID: 426ed32bc20a
Revises: df1565f5e031
Create Date: 2025-10-06 21:36:44.332617

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "426ed32bc20a"
down_revision = "df1565f5e031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "story_script",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("sub_title", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("author_note", sa.String(length=300), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("author_final_comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("story_script_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_script")
    # ### end Alembic commands ###
