"""create app tables

Revision ID: e82aaa7ce510
Revises: d4745a74668c
Create Date: 2025-10-16 12:39:34.538700

"""



# revision identifiers, used by Alembic.
revision = "e82aaa7ce510"
down_revision = "d4745a74668c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
