"""create art model

Revision ID: 2466d81beadf
Revises: 426ed32bc20a
Create Date: 2025-10-07 07:12:30.498123

"""



# revision identifiers, used by Alembic.
revision = "2466d81beadf"
down_revision = "426ed32bc20a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
