"""create migration new art

Revision ID: 8dd51b079752
Revises: 2466d81beadf
Create Date: 2025-10-07 07:36:09.924394

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8dd51b079752"
down_revision = "2466d81beadf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "art",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("description", sa.String(length=300), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("art")
    # ### end Alembic commands ###
