"""adiciona_autoincremento_id_tabela_art

Revision ID: c806f1e3ba13
Revises: 6f419c4d57d8
Create Date: 2025-10-07 08:09:41.871254

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c806f1e3ba13"
down_revision = "6f419c4d57d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("art", "title", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column(
        "art", "description", existing_type=sa.VARCHAR(length=300), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "art", "description", existing_type=sa.VARCHAR(length=300), nullable=True
    )
    op.alter_column("art", "title", existing_type=sa.VARCHAR(length=50), nullable=True)
    # ### end Alembic commands ###
