name: CD - Deploy to Render

on:
  workflow_run:
    workflows:
      - CI - Validate & Test
    branches:
      - main
    types:
      - completed

concurrency:
  group: render-deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    name: Trigger Render deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Deploy services via Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_IDS: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -euo pipefail
          if [ -z "${RENDER_API_KEY}" ] || [ -z "${RENDER_SERVICE_IDS}" ]; then
            echo "Render secrets not configured (RENDER_API_KEY / RENDER_SERVICE_ID)."
            exit 1
          fi

          IFS=',' read -ra SERVICES <<< "${RENDER_SERVICE_IDS}"
          for service in "${SERVICES[@]}"; do
            SERVICE_ID="$(echo "${service}" | xargs)"
            if [ -z "${SERVICE_ID}" ]; then
              continue
            fi

            echo "Triggering deploy for Render service '${SERVICE_ID}'."
            curl -fsS -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
              -H "Accept: application/json" \
              -H "Authorization: Bearer ${RENDER_API_KEY}" \
              -H "Content-Type: application/json"
          done
